# Generated by Django 5.1 on 2025-11-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='test_attempted',
            field=models.IntegerField(default=0),
        ),
    ]
